[package]
name = "code_gen_test_enclave_gen"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
doc = false
doctest = false

[dependencies]
edlcodegen-enclave = { git = "https://github.com/microsoft/VbsEnclaveTooling", subdir = "rust" }
flatbuffers = "25.9.23"
